- .buildkite/custom-tests.json
- crates/vfio-bindings/Cargo.toml
- crates/vfio-ioctls/Cargo.toml
Prepare for publishing vfio-ioctls v0.1.0. Support of mshv is disabled temporarily and will be enabled once v0.1.0 has been published.
> Prepare for publishing vfio-ioctls v0.1.0

- coverage_config_x86_64.json
- crates/vfio-bindings/src/bindings_v5_0_0/mod.rs
This PR includes the original one from dependabot https://github.com/rust-vmm/vfio/pull/5
It fixes clippy warnings and test coverage due to updated Rust version.
> Fix warnings and adjust test coverage

- .buildkite/custom-tests.json
- crates/vfio-ioctls/Cargo.toml
The vfio-ioctls v0.1.0 has been published, so reenable support of mshv.
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>
> ioctls: reenable support of mshv

- crates/vfio-ioctls/src/lib.rs
- crates/vfio-ioctls/src/vfio_device.rs
While trying to make Cloud Hypervisor work for KVM and MSHV at the same time, I realize that leaking dependent types is a bad idea. That requires library users to provide different code paths depending on the features.
This PR provides a vfio-ioctls wrapper type which can hold either a KVM DeviceFd or MSHV DeviceFd. Unfortunately these are breaking changes.
Since I'm making breaking changes anyway, I slip in an extra patch to make a DeviceFd optional. This makes this crate useful for people who wants VFIO but have no need for a VM.
requirements:
message has max 60 characters for the summary and max 75 characters for each
description line.
test.
> RFC: New APIs for vfio-ioctls

- crates/vfio-ioctls/src/lib.rs
- crates/vfio-ioctls/src/vfio_device.rs
- crates/vfio-ioctls/src/vfio_ioctls.rs
Improving the error that is reported through IommuDmaMap and IommuDmaUnmap
by propagating the system error retrieved through SysError.
Also introducing new types of VfioError to provide more appropriate errors
to the caller.
Signed-off-by: xuejun-xj <jiyunxue@linux.alibaba.com>
Signed-off-by: jingshan <jingshan@linux.alibaba.com>
This PR enables VfioError::IommuDmaMap/IommuDmaUnmap to take SysError after calling the ioctls. 
Issue: #12
> vfio_device: enable IommuDmaMap/IommuDmaUnmap to take SysError

- coverage_config_x86_64.json
- crates/vfio-bindings/Cargo.toml
- crates/vfio-ioctls/Cargo.toml
And also bump the crate versions as well as the dependency versions.
See: rust-vmm/community#136
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
> build: Use caret dependencies for Rust-VMM crates

- crates/vfio-ioctls/src/lib.rs
- crates/vfio-ioctls/src/vfio_device.rs
- crates/vfio-ioctls/src/vfio_ioctls.rs
*The vfio-rs framewrok only supports PCI devices at present. This PR aims at adding support for platform devices.*
> vfio-ioctls: support platform devices to use vfio framework

- crates/vfio-ioctls/src/lib.rs
- crates/vfio-ioctls/src/vfio_device.rs
KVM uses resamplefd to enables level triggered interrupts to be posted and re-enabled from vfio with no userspace intervention.  Currently vfio-ioctl doesn't provide an interface for registering resamplefd, so vmm must guess the intx eoi by trapping the write/read_bar, and re-enable(unmask) the interrupt in write/read_bar. Here we introduce  a new interface set_irq_resample_fd()  to set resamplefd to vfio that allow vfio automatically unmask the interrupt in the kernel.
> Uses resamplefd to bypass userspace VMM INTx EOI handling

- crates/vfio-ioctls/Cargo.toml
The purpose is to enable VMMs (cloud-hypervisor) use kvm device file other than `/dev/kvm`. See https://github.com/rust-vmm/kvm-ioctls/commit/3de4150068183b640ac307ac47674bbc8e7c8695 .
bumping kvm-ioctls version to resolve the following error:
```
error[E0308]: mismatched types
--> hypervisor/src/kvm/mod.rs:330:39
|
330 |         Ok(VfioDeviceFd::new_from_kvm(device_fd))
|            -------------------------- ^^^^^^^^^ expected struct `kvm_ioctls::ioctls::device::DeviceFd`, found struct `DeviceFd`
|            |
|            arguments to this function are incorrect
|
= note: perhaps two different versions of crate `kvm_ioctls` are being used?
```
message has max 60 characters for the summary and max 75 characters for each
description line.
test.
Release" section of CHANGELOG.md (if no …
> build(deps): bump kvm-ioctls from 0.12.0 to 0.13.0

- crates/vfio-ioctls/Cargo.toml
This PR bumps `vm-memory` from 0.10.0 to 0.11.0 so that the consumers of the `vfio` crates (e.g. Cloud Hypervisor) can also bump to use latest `vm-memory` crate.
requirements:
message has max 60 characters for the summary and max 75 characters for each
description line.
test.
> build: Bump vm-memory from 0.10.0 to 0.11.0

- crates/vfio-ioctls/Cargo.toml
https://github.com/rust-vmm/vm-memory/releases/tag/v0.12.0
requirements:
message has max 60 characters for the summary and max 75 characters for each
description line.
test.
> build: Bump vm-memory from 0.11.0 to 0.12.0

- crates/vfio-ioctls/src/vfio_ioctls.rs
This fixes a clippy warning.
requirements:
test.
> vfio-ioctls: use std::mem::size_of_val

- README.md
Crate urls in `README.md` pointed to `vfio-ioctl` which is an archived repository.
requirements:
test.
> Fix crate urls in README.md

- crates/vfio-ioctls/src/vfio_device.rs
Passing an fd from user-space to the kernel requires native endianess. Change LittleEndian to NativeEndian to also support big endian machines.
@epilys  I think commit 07fd7ef3a1c2 ("vfio/pci: Use endian neutral helpers") is only tangentially related and as the commit message states did not change the observed behavior. As I understand it, that commit is about MMIO via pread() from the device fd which keeps the endianess of the read unchanged. This makes sense since it keeps the observed data consistent between pread() from the device fd and mmap() of the same fd where a load is then MMIO which for PCI is always little endian. For the case I encountered, this is about passing an fd from user-space to the kernel which requires native endianess.
> Fix endianess for fd's

- crates/vfio-ioctls/src/vfio_device.rs
- crates/vfio-ioctls/src/vfio_ioctls.rs
vfio_pci driver returns num_regions of at least [VFIO_PCI_NUM_REGIONS](https://elixir.bootlin.com/linux/v6.6.33/source/drivers/vfio/pci/vfio_pci_core.c#L978) from [VFIO_DEVICE_GET_INFO](https://elixir.bootlin.com/linux/v6.6.33/C/ident/VFIO_DEVICE_GET_INFO) ioctl.
However, if the device does not support VGA, the [VFIO_DEVICE_GET_REGION_INFO](https://elixir.bootlin.com/linux/v6.6.33/C/ident/VFIO_DEVICE_GET_REGION_INFO) ioctl returns -EINVAL for [VFIO_PCI_VGA_REGION_INDEX](https://elixir.bootlin.com/linux/v6.6.33/C/ident/VFIO_PCI_VGA_REGION_INDEX).
Currently, an error is logged for this case, but a device not supporting VGA is not an error, so this particular -EINVAL is intended and correct for devices without VGA regions.
Two fixes:
1. make the ioctl wrappers return the actual errno errors, …
> vfio-ioctls: fix get_region_info VFIO_PCI_VGA_REGION_INDEX error

- crates/vfio-ioctls/Cargo.toml
Note v0.3.0 has breaking changes that require changes in downstream code. Bumping mshv-ioctls version in vfio-ioctls is a dependency for updating the downstream code.
requirements:
- [ x ] All commits in this PR have Signed-Off-By trailers (with
- [ x ] All added/changed functionality has a corresponding unit/integration
test.
- [ x ] All added/changed public-facing functionality has entries in the "Upcoming 
- [ x ] Any newly added `unsafe` code is properly documented.
> vfio-ioctls: pin mshv crate to tag: v0.3.0

- crates/vfio-ioctls/Cargo.toml
- crates/vfio-ioctls/src/vfio_device.rs
Move mshv crates from v0.3.1 to v0.3.2
requirements:
test.
> vfio-ioctls: Bump mshv crates to latest version

- CODEOWNERS
- Cargo.toml
- crates/vfio-ioctls/Cargo.toml
- crates/vfio-ioctls/src/vfio_device.rs
We have active development on MSHV side, after updated the MSHV version we also need to pin that version in VFIO in order to use in Cloud-Hypervisor project. After adding me as the maintainer I can expedite the MSHV related PRs.
*Please summarize here why the changes in this PR are needed.*
requirements:
test.
> Add @russell-islam  as code owner

- vfio-bindings/CONTRIBUTING.md
- vfio-bindings/src/bindings_v5_0_0/vfio.rs
- vfio-ioctls/src/vfio_ioctls.rs
Auto-generated bindings are not supposed to be modified manually. Instead, it is
less error prone to ensure type compatibility from the consumer of the bindings,
such as 'vfio-ioctls' crate.
This patch also takes the opportunity to improve the CONTRIBUTING.md:
* Clarify the version of `bindgen` being used;
* Enable `--impl-debug` and `--impl-partialeq` with bindgen;
requirements:
test.
> vfio-bindings: Avoid manual modifications to auto-generated code

- vfio-user/examples/gpio/main.rs
- vfio-user/examples/gpio/pci.rs
Fixed the following issue with `$cargo clippy --fix`:
error: manual implementation of `.is_multiple_of()`
--> vfio-user/examples/gpio/pci.rs:406:12
|
406 |         if offset % 4 != 0 {
|            ^^^^^^^^^^^^^^^ help: replace with: `!offset.is_multiple_of(4)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_is_multiple_of
= note: `-D clippy::manual-is-multiple-of` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::manual_is_multiple_of)]`
*Please summarize here why the changes in this PR are needed.*
requirements:
summary and max 75 characters for each …
> vfio-user: Fix beta clippy issues

- Cargo.toml
- vfio-bindings/CHANGELOG.md
- vfio-ioctls/CHANGELOG.md
- vfio-ioctls/Cargo.toml
- vfio-user/CHANGELOG.md
- vfio-user/Cargo.toml
thiserror -> 2.0.12 to 2.0.16
vmm-sys-util -> 0.14.0 to 0.15.0
kvm-bindings -> 0.12.0 to 0.14.0
kvm-ioctls -> 0.22.0 to 0.24.0
bitflags -> 2.9.0 to 2.9.4
requirements:
test.
> Cargo.toml: Update deps to latest version

- vfio-ioctls/src/lib.rs
- vfio-ioctls/src/vfio_device.rs
To support advanced hardware features, the vfio subsystem now supports multiple modes, e.g. the legacy vfio mode using container and groups, and the new vfio cdev mode (#92). 
The current design and implementation of `vfio-ioctls` crate only supports legacy mode. Here is a proposal to refactor its design to support both modes.
* Adopt 'KVM_DEV_VFIO_FILE*' uAPIs to accept vfio device files from userspace using both mode;
* Introduce `struct VfioCommon` to hold common data structure used by both mode;
* Make `struct VfioDevice` and `struct VfioDeviceInfo` mode agnostic (decoupling specifics of vfio container and groups);
The public APIs exposed to user-space (say VMM) now are defined via a public trait:
```
/// Trait to define common operations exposed to user-space drivers for
/// VFIO …
```
> Refactor for supporting multiple VFIO interfaces: both legacy mode and cdev mode using iommufd
